### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by dzg** [dhleong/pepper-mint#38]
Trying this out again:

```javascript
require('pepper-mint')(user, pass)
```

Gives

```javascript
Promise {
 <pending>,
 mint: PepperMint {
   _events: [Object: null prototype] {},
   _eventsCount: 0,
   _maxListeners: undefined,
   net: RequestNetService {
     jar: [RequestJar],
     request: [Function],
     requestId: 42
   },
   auth: DeferredAuth {},
   clock: Clock {},
   cache: Cache { cache: {} },
   intuitApiKey: '..........',
   [Symbol(kCapture)]: false
 },
 [Symbol(async_id_symbol)]: 31016,
 [Symbol(trigger_async_id_symbol)]: 5,
 [Symbol(destroyed)]: { destroyed: false }
}
```

... and a Chrome window opens for a moment, but immediately closes.

Then finally:

```javascript
> Uncaught WebDriverError: element not interactable
 (Session info: chrome=96.0.4664.110)
 (Driver info: chromedriver=95.0.4638.54 (d31a821ec901f68d0d34ccdbaea45b4c86ce543e-refs/branch-heads/4638@{#871}),platform=Mac OS X 10.15.7 x86_64)
   at Object.checkLegacyResponse (/Users/zeev/node_modules/selenium-webdriver/lib/error.js:546:15)
   at parseHttpResponse (/Users/zeev/node_modules/selenium-webdriver/lib/http.js:509:13)
   at /Users/zeev/node_modules/selenium-webdriver/lib/http.js:441:30
   at runMicrotasks (<anonymous>)
   at processTicksAndRejections (node:internal/process/task_queues:96:5)
From: Task: WebElement.sendKeys()
   at Driver.schedule (/Users/zeev/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
   at WebElementPromise.schedule_ (/Users/zeev/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
   at WebElementPromise.sendKeys (/Users/zeev/node_modules/selenium-webdriver/lib/webdriver.js:2174:19)
   at ChromedriverMintAuth.<anonymous> (/Users/zeev/node_modules/pepper-mint/dist/auth/chromedriver-auth.js:41:80)
   at Generator.next (<anonymous>)
   at fulfilled (/Users/zeev/node_modules/pepper-mint/dist/auth/chromedriver-auth.js:5:58)
   at runMicrotasks (<anonymous>)
   at processTicksAndRejections (node:internal/process/task_queues:96:5) {
 remoteStacktrace: ''
}
```

**Comment by dhleong** [comment]
I've been getting somewhat regular PRs to support newer versions of Chrome,
but I don't actively use it anymore myself. I'd be happy to check out a PR
if you'd like to submit a fix, however!
